### ISSUE TITLE
Door won't open

### ISSUE THREAD

**Issue by SerSquirt** [cadergator10/opencomputer-security-system#24]
**Describe the bug**
Door doesn't open when the card is swiped, even though everything is plugged in correctly, and it says Access Granted.

**Expected behavior**
The door should open as normal.

**Screenshots**
![image](https://user-images.githubusercontent.com/54420277/208202849-7c01ae3c-3e63-4438-94bd-8b71a77b4737.png)
_The door setup_
![image](https://user-images.githubusercontent.com/54420277/208204109-1d189bcd-1ca3-4bae-b20f-14ed3432e345.png)
_Diagnostics Tablet_
![image](https://user-images.githubusercontent.com/54420277/208204215-e8f07248-65c7-44ed-8750-9fe28ed58953.png)
_The door controller is connected properly, as the door opens._

**Mod versions:**
 -Open Computers version: #1.7.7
 -Open Security version: #1.0-92

**Additional context**
The Door Controller does not show up when scanning the door with the Diagnostics Tablet, and when doorcontroller.open() is run in lua, the door opens as expected.

**Comment by cadergator10** [comment]
So 1st, one of those cables can be removed, either the top or bottom. If devices are touching, then they automatically get connected
It looks like that the device crashes when it gets to the part where it either prints out the controllers or when it checks the door type.

The only thing I can think of is an incorrectly typed out doortype or a bug in the finish code...

Is there a chance you could send me the world save? That's the easiest way I can see to check the configuration of the door to find the error

**Comment by cadergator10** [comment]
Scratch that: I found and fixed the issue. If you delete all files added on the doorcomputer and resetup the door on the database, it should work this time.
There was something stupid with the finish program deciding to only look for rolldoors during single door setup, and since you didn't have any, there was nothing under door address. This was causing the diagnostic thread to crash, which is why it abrubtly stopped at "reader address", because below that is where it's supposed to tell you the door address.
I could have sworn it worked earlier. I think some issues with github I had earlier. I hope this fixes it!

Edit: Make sure you reinstall all the modules though, because the finish program is saved to your mineos database
Edit #2: Apparently, there was also something up with the address to all the rolldoor and door controllers was incorrect. Don't know if they changed the address or I'm stupid, but it works. The things I find months after I temporarilly stop development. Thank you for bringing light to this issue :)

**Comment by SerSquirt** [comment]
It's still not working... I've deleted all files on the door computer,  made sure to reinstall the modules, but it still doesn't work. I've noticed some more things, though. I was able to make a rolldoor just fine, and it works perfectly, unlike the regular door. Also, when running the finish program it just asks me which sector i would like the door to be in, which i choose none, then it says all set. It seems like there should be more steps there.

Edit: Another thing, whenever i try scanning the door with the updated diagnostics, it now says "There was an exception in the diagnostic thread on that last door: please report to github"

**Comment by cadergator10** [comment]
That exception thing was a check I added so the user would know that there was an exception, so that's good that it worked

As for the roll door vs the regular door, i'll check into that right now. As for why it only asks for the sector, if you set up all the stuff inside the database (except for sector of course because that dropdown is broke atm) then that would be the only thing it would need. If you want to try it, try leaving the door delay empty instead of putting a number there. It should ask you for the delay.

**Comment by cadergator10** [comment]
alright, i KNOW (that means I think now that I've failed once lol) that I fixed it now. On top of that, the sector button should work now, yey! So you can set the sector if you have one and want to now in the database. :)

**Comment by SerSquirt** [comment]
It works now, thanks so much for fixing! This security system will be really helpful on my modded server!
