### ISSUE TITLE
Add keypad, RFID, biometric support

### ISSUE THREAD

**Issue by autodoorsdev** [cadergator10/opencomputer-security-system#36]
As the title says right now we can only use magcards. But it would be super cool if we could use keypads, RFID readers, and the other readers that OpenSecurity offers with this door system.

I have no idea if there is any hidden functionality that enables these features but it would be cool if you added support for the above readers

**Comment by cadergator10** [comment]
I'll probably try and add this with the next rewrite. There were a few reasons I haven't added these in.

Magnetic reader is simple and straight forward: just swipe the card and it trips an event to respond to. It's also straight forward what controls what

RFID reader suffers in most of these areas. In order to detect a card, you have to call a function on the block over and over and over on every reader in order to detect it. This can lead to potential lag (I'm assuming, haven't tested). Also if doors are close together, it may be difficult to only open one door. But these can be handled by the user using it, so it doesn't matter so much.

Keypad doesn't make too much sense on the system, although I guess it could be helpful to have global passwords in place for keypads.

Biometric reader could likely be done througha SecurityAPI program, but I could try adding a default variable in the security database to link users to cards.

An update like this is gonna take a while, especially since I'm working rn on a server for servertine to download modules from.

**Comment by enderman-2009** [comment]
for keypad maybe you could assign pass with a pin

**Comment by cadergator10** [comment]
> for keypad maybe you could assign pass with a pin

I have an idea for it. Basically there will be another tab for the security module for the keypad pins. Then you can assign multiple of these keys to a keypad so all that you want to work with it will. You can also choose to add manual pins (per keypad codes) instead of global ones if you want to.

Oh but now looking at it you're suggesting that someone gets a pass on their account if they enter a certain pin. I don't think I'll be adding that in the future unless I think of a good way to implement them in a good and simple way.

**Comment by enderman-2009** [comment]
like with a card but instead its a pin so you can't steal it

**Comment by cadergator10** [comment]
> like with a card but instead its a pin so you can't steal it

Ah I see what you mean. I likely won't add that to the keypads, but I am adding biometric reader support, which should allow you to attach users to players

**Comment by enderman-2009** [comment]
the thing is cards are great but if you get one stolen you need to reset it then print another one and if you for example put the computers behind the door you can't access it anymore and so you can't reset it so the person that has the card can just get the crypt key and decrypt your user's name and password and have access to the entire thing

**Comment by cadergator10** [comment]
> the thing is cards are great but if you get one stolen you need to reset it then print another one and if you for example put the computers behind the door you can't access it anymore and so you can't reset it so the person that has the card can just get the crypt key and decrypt your user's name and password and have access to the entire thing

That's true, but keypads will get added, so you could add a password only for that door, and also the biometric reader could achieve the same thing but without getting stolen.

**Comment by cadergator10** [comment]
Feature has been added is likely to be released later today. Closing for completion
